from typing import Literal

from pydantic import BaseModel, Field


class ChunkWithMetadata(BaseModel):
    """A retrieved document chunk with its source metadata."""

    chunk_id: str = Field(description="Unique chunk identifier.")
    document_id: str = Field(description="Unique document (file id) identifier.")
    source: str = Field(description="Source document path.")
    page: int = Field(description="Zero-based page index.")
    start_index: int = Field(description="Chunk start offset in page.")
    content: str = Field(description="Chunk text content.")


class CitedChunk(ChunkWithMetadata):
    """A chunk that supports an answer, paired with its inline citation index.

    Extends ChunkWithMetadata with citation_index, which matches
    the inline [N] marker rendered in the answer text.
    """

    citation_index: int = Field(description="Inline [N] marker in the answer.")


class QueryRequest(BaseModel):
    """Request body for the /query endpoint."""

    query: str = Field(min_length=1, description="User question to answer.")


class LlmUsage(BaseModel):
    """Token usage for the RAG generation LLM call."""

    input_tokens: int = Field(description="Tokens sent to the model (prompt + context).")
    output_tokens: int = Field(description="Tokens generated by the model.")
    total_tokens: int = Field(description="input_tokens + output_tokens.")
    cached_tokens: int | None = Field(
        default=None,
        description="Input tokens served from the provider prompt cache.",
    )
    reasoning_tokens: int | None = Field(
        default=None,
        description="Output tokens used for internal reasoning (model-dependent).",
    )


class QueryResponse(BaseModel):
    """Response body for the /query endpoint."""

    answer: str = Field(description="Answer text with inline [N] citation markers.")
    cited_chunks: list[CitedChunk] = Field(
        description="Chunks supporting the answer, in citation order."
    )
    usage: LlmUsage | None = Field(
        default=None,
        description="RAG LLM token usage; null when generation was skipped.",
    )


class HealthResponse(BaseModel):
    """Response body for the /health endpoint."""

    status: str = Field(description="Service health status.")


class DocumentItem(BaseModel):
    document_id: str = Field(description="PDF basename on disk.")
    filename: str = Field(description="PDF basename on disk.")


class DocumentsResponse(BaseModel):
    """Response body for the /documents endpoint."""

    documents: list[DocumentItem] = Field(description="Stored PDFs.")


class UploadResponse(BaseModel):
    """Response body for the /upload endpoint."""

    document_id: str = Field(description="PDF basename on disk.")
    filename: str = Field(description="PDF basename on disk.")


StreamProgressStage = Literal["retrieval", "rerank", "inference"]


class StreamEventBase(BaseModel):
    """Shared envelope for all V1 stream events."""

    stream_version: Literal[1] = Field(default=1)
    request_id: str = Field(description="Unique request identifier for this stream.")
    sequence: int = Field(description="Monotonic event sequence number, starting at 1.")
    timestamp_ms: int = Field(description="Server-side Unix epoch timestamp in milliseconds.")


class StreamStartEvent(StreamEventBase):
    """First event in the V1 stream lifecycle."""

    type: Literal["start"] = "start"
    query: str = Field(description="Original user query text.")


class StreamProgressEvent(StreamEventBase):
    """Pipeline milestone event emitted during retrieval, reranking, or model inference."""

    type: Literal["progress"] = "progress"
    stage: StreamProgressStage = Field(
        description=(
            "Pipeline phase: retrieval and rerank select context; inference covers "
            "the forward pass / streamed answer from the language model (including "
            "time until streamed tokens begin)."
        ),
    )
    message: str = Field(description="Human-readable progress message.")


class StreamDeltaEvent(StreamEventBase):
    """Incremental answer text emitted while the LLM streams tokens."""

    type: Literal["delta"] = "delta"
    delta: str = Field(description="Answer text chunk to append on the client.")


class StreamCompleteEvent(StreamEventBase):
    """Terminal success event with the canonical final answer payload."""

    type: Literal["complete"] = "complete"
    data: QueryResponse = Field(
        description="Final canonical answer payload including cited chunks."
    )
    timings_ms: dict[str, int] = Field(
        description=(
            "Timing milestones in milliseconds from stream start: pipeline stages "
            "(e.g. retrieval, rerank, inference), first_token_ms (time to first answer "
            "text delta), and total end-to-end elapsed time."
        ),
    )
    usage: LlmUsage | None = Field(
        default=None,
        description="RAG LLM token usage; null when generation was skipped.",
    )


class StreamFailedEvent(StreamEventBase):
    """Terminal failure event with stable error code and display-safe message."""

    type: Literal["failed"] = "failed"
    code: Literal["internal_error"] = "internal_error"
    message: str = Field(description="User-safe error message.")
